//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int id { get; set; }
        public int count { get; set; }
        public string total_cost { get; set; }
        public System.DateTime date { get; set; }
        public int sellers_id { get; set; }
        public int products_id { get; set; }
    
        public virtual products products { get; set; }
        public virtual sellers sellers { get; set; }
    }
}
