//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interYOURMOMface
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public int credit_number { get; set; }
        public string percent_set { get; set; }
        public string currency { get; set; }
        public System.DateTime credit_start { get; set; }
        public System.DateTime credit_end { get; set; }
        public string remainer { get; set; }
        public string sum { get; set; }
        public string month_sum { get; set; }
        public string months { get; set; }
    
        public virtual card card { get; set; }
        public virtual customer customer { get; set; }
    }
}
