//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loans_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int card_id { get; set; }
        public string IL { get; set; }
        public string card_type { get; set; }
        public string system_code { get; set; }
        public string bank_code { get; set; }
        public string bill_number { get; set; }
        public string check_number { get; set; }
        public string cvv { get; set; }
        public System.DateTime card_start { get; set; }
        public System.DateTime card_end { get; set; }
        public string check_word { get; set; }
    
        public virtual credit credit { get; set; }
    }
}
